/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 死活監視（DB まで見る） */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ダッシュボードの初回表示ぶん */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の実績の一覧（新しい日付から。同じ日は記録した順） */
        get: operations["listStudyLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-logs/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 日ごとの合計学習時間（新しい日付から） */
        get: operations["listDailyStudyMinutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の予定の一覧（古い日付から。同じ日は作った順） */
        get: operations["listStudyPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 志望校の一覧（学部・大学・学部のタグつき。作った順） */
        get: operations["listGoals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/first-choice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 第一志望（トップの表示用。タグは付けない） */
        get: operations["getFirstChoiceGoal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の参考書の一覧（名前順） */
        get: operations["listTextbooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbook-masters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 参考書マスターの一覧（総量の候補つき。全員に同じもの） */
        get: operations["listTextbookMasters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の通知設定（保存していなければ全部 false） */
        get: operations["getNotificationPreferences"];
        /** 自分の通知設定を保存する（無ければ作る） */
        put: operations["saveNotificationPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 自分のニックネームを変える */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 大学を探す画面の一覧（全員に同じもの）
         * @description サーバーは JSON をメモリに持ち、ETag を付ける。If-None-Match が合えば 304 で本文を省く。 Accept-Encoding が gzip を受け付けるなら、圧縮済みの形を返す。
         */
        get: operations["listUniversities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 大学詳細（学部・タグと、自分が志望校に登録済みの学部 ID） */
        get: operations["getUniversity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/daily-study-notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 毎日の学習通知を送る（EC2 の systemd timer が朝7時・夜21時に呼ぶ） */
        post: operations["sendDailyStudyNotifications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 本登録の完了を GA4 に送ってよいか（初回だけ true。2回目以降は false）
         * @description 本文は読まない（送られても使わない）
         */
        post: operations["trackRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csp-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ブラウザが送る CSP の違反の報告。ログにだけ残す（DB には書かない）
         * @description report-uri（application/csp-report）と report-to（application/reports+json）の両方の形を受ける。 読めない本文でも 204（ブラウザに送り直させない）。本文は 16KB まで、1回に読む報告は20件まで
         */
        post: operations["reportCspViolation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** シミュレーションの合成ユーザーの一覧と、次に使う連番（SIMULATION_ENABLED=on のときだけある） */
        get: operations["getSimulationState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登録を済ませた合成ユーザーに、連番と続き方の型を付ける */
        post: operations["markSimulationUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/users/{seq}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 最後に操作した日・来なくなった日を記録する（キーが無い項目は変えない） */
        patch: operations["updateSimulationUser"];
        trace?: never;
    };
    "/api/line/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LINE と連携しているか（プロフィール画面） */
        get: operations["getLineConnection"];
        put?: never;
        post?: never;
        /** LINE との連携を解除する。LINE の通知設定も切る */
        delete: operations["disconnectLine"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/account-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** トークから始めた連携（Account Link）で、使い捨ての nonce を発行して LINE の連携画面の URL を返す */
        post: operations["startLineAccountLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LINE Login を始める（画面遷移。未ログインはログイン画面へ） */
        get: operations["startLineLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LINE Login の戻り先。結果はプロフィール画面へ ?line=<結果> で知らせる */
        get: operations["completeLineLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LINE の Webhook。署名（x-line-signature）を本文のまま確かめ、同じイベントの再送は処理しない */
        post: operations["receiveLineWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: date-time
         * @description Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
         */
        IsoDateTime: string;
        /**
         * Format: date
         * @description 日付だけ（"YYYY-MM-DD"、日本時間の日付）
         */
        IsoDate: string;
        LineConnectionStatus: {
            connected: boolean;
        };
        /** @description ルートが自分で断るときのエラー。error は画面にそのまま出す文言 */
        Error: {
            error: string;
        };
        /** @description 入力チェックで弾いたときのエラー（Node の routes/validation-error.ts、Go の query.go） */
        ValidationError: {
            /** @description 画面にそのまま出す文言 */
            error: string;
            /** @description 種類。自分で書いた規則は名前（range_end_before_start など）、 組み込みのチェックは Zod の code（too_small・invalid_type・invalid_format など） */
            code: string;
            /** @description どの項目か（"rangeEnd"・"items.0.unit"）。項目に結びつかなければ null */
            field: string | null;
        };
        /** @description 想定外の失敗・混雑・存在しないパス */
        ServerError: {
            error: string;
            /** @enum {string} */
            code: "INTERNAL_ERROR" | "OVERLOADED" | "NOT_FOUND" | "FST_ERR_CTP_BODY_TOO_LARGE" | "FST_ERR_CTP_INVALID_MEDIA_TYPE" | "FST_ERR_CTP_INVALID_CONTENT_LENGTH";
            reqId: string;
        };
        /** @description プロフィールの更新（Zod の profileSchema）。長さはコードポイントの数（絵文字も1）で数え、 前後の空白は長さを確かめた後に削る（空白だけでも通り、空文字で保存される） */
        ProfileInput: {
            nickname: string;
        };
        /** @description 利用者の行（PUT /api/profile が返す） */
        User: {
            id: string;
            name: string | null;
            email: string | null;
            image: string | null;
            nickname: string | null;
            createdAt: components["schemas"]["IsoDateTime"];
            updatedAt: components["schemas"]["IsoDateTime"];
            emailVerified: boolean;
            firstStudyLogAt: components["schemas"]["IsoDateTime"] | null;
            analyticsSignUpTrackedAt: components["schemas"]["IsoDateTime"] | null;
        };
        /** @description 実績・予定に JOIN した参考書（表示用） */
        Textbook: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            masterId: number | null;
            name: string;
            /** Format: int64 */
            totalAmount: number | null;
            rangeUnit: string | null;
            targetDate: components["schemas"]["IsoDateTime"] | null;
            subject: string | null;
        };
        StudyLog: {
            /** Format: int64 */
            id: number;
            date: components["schemas"]["IsoDateTime"];
            /** Format: int64 */
            minutes: number;
            subject: string | null;
            /** Format: int64 */
            textbookId: number | null;
            textbook: components["schemas"]["Textbook"] | null;
            /** Format: int64 */
            rangeStart: number | null;
            /** Format: int64 */
            rangeEnd: number | null;
            rangeUnit: string | null;
            memo: string | null;
            /** Format: int64 */
            studyPlanId: number | null;
        };
        StudyPlan: {
            /** Format: int64 */
            id: number;
            date: components["schemas"]["IsoDateTime"];
            content: string | null;
            subject: string | null;
            done: boolean;
            /** Format: int64 */
            studyLogId: number | null;
            /** Format: int64 */
            textbookId: number | null;
            textbook: components["schemas"]["Textbook"] | null;
            /** Format: int64 */
            rangeStart: number | null;
            /** Format: int64 */
            rangeEnd: number | null;
            rangeUnit: string | null;
        };
        DailyStudyMinutes: {
            date: components["schemas"]["IsoDateTime"];
            /** Format: int64 */
            minutes: number;
        };
        /** @description 両端を含む期間（"YYYY-MM-DD"） */
        DateRange: {
            from: components["schemas"]["IsoDate"];
            to: components["schemas"]["IsoDate"];
        };
        Dashboard: {
            /** @description 今日の月（"YYYY-MM"） */
            month: string;
            logRange: components["schemas"]["DateRange"];
            logs: components["schemas"]["StudyLog"][];
            planRange: components["schemas"]["DateRange"];
            plans: components["schemas"]["StudyPlan"][];
            dailyMinutes: components["schemas"]["DailyStudyMinutes"][];
        };
        Tag: {
            /** Format: int64 */
            id: number;
            name: string;
            createdAt: components["schemas"]["IsoDateTime"];
        };
        University: {
            /** Format: int64 */
            id: number;
            name: string;
            prefecture: string;
            type: string;
            createdAt: components["schemas"]["IsoDateTime"];
        };
        /** @description 学部（大学を入れ子にしない） */
        Faculty: {
            /** Format: int64 */
            id: number;
            name: string;
            examDate: components["schemas"]["IsoDateTime"];
            createdAt: components["schemas"]["IsoDateTime"];
            /** Format: int64 */
            universityId: number;
        };
        FacultyWithTags: components["schemas"]["Faculty"] & {
            tags: components["schemas"]["Tag"][];
        };
        FacultyWithUniversity: components["schemas"]["Faculty"] & {
            university: components["schemas"]["University"];
        };
        FacultyWithUniversityAndTags: components["schemas"]["FacultyWithUniversity"] & {
            tags: components["schemas"]["Tag"][];
        };
        /** @description 志望校の列（学部は含まない） */
        GoalFields: {
            /** Format: int64 */
            id: number;
            createdAt: components["schemas"]["IsoDateTime"];
            userId: string;
            /** Format: int64 */
            facultyId: number;
            isFirstChoice: boolean;
            note: string | null;
            status: string;
        };
        /** @description 志望校の一覧の1件。学部・大学・学部のタグつき */
        Goal: components["schemas"]["GoalFields"] & {
            faculty: components["schemas"]["FacultyWithUniversityAndTags"];
        };
        /** @description 第一志望。学部・大学つき（タグは付けない） */
        FirstChoiceGoal: components["schemas"]["GoalFields"] & {
            faculty: components["schemas"]["FacultyWithUniversity"];
        };
        /** @description 自分の参考書（DB の行そのまま） */
        TextbookRow: {
            /** Format: int64 */
            id: number;
            userId: string;
            /** Format: int64 */
            masterId: number | null;
            name: string;
            /** Format: int64 */
            totalAmount: number | null;
            rangeUnit: string | null;
            targetDate: components["schemas"]["IsoDateTime"] | null;
            subject: string | null;
            createdAt: components["schemas"]["IsoDateTime"];
            updatedAt: components["schemas"]["IsoDateTime"];
        };
        TextbookMasterMetric: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            masterId: number;
            unit: string;
            /** Format: int64 */
            totalAmount: number;
            isDefault: boolean;
            createdAt: components["schemas"]["IsoDateTime"];
            updatedAt: components["schemas"]["IsoDateTime"];
        };
        TextbookMaster: {
            /** Format: int64 */
            id: number;
            name: string;
            publisher: string | null;
            edition: string | null;
            isbn: string;
            createdAt: components["schemas"]["IsoDateTime"];
            updatedAt: components["schemas"]["IsoDateTime"];
            /** @description 総量の候補（id 順）。無くても [] */
            metrics: components["schemas"]["TextbookMasterMetric"][];
        };
        NotificationPreference: {
            emailMorningEnabled: boolean;
            emailEveningEnabled: boolean;
            lineMorningEnabled: boolean;
            lineEveningEnabled: boolean;
        };
        /** @description 大学を探す画面の1件。画面が使うのは大学の列と学部ごとのタグ名だけ。 Go はこの形を手書きの型で返す（JSON のキーの順番を Node と同じにして ETag をそろえるため） */
        ExploreUniversity: {
            /** Format: int64 */
            id: number;
            name: string;
            prefecture: string;
            type: string;
            faculties: components["schemas"]["ExploreFaculty"][];
        };
        ExploreFaculty: {
            tags: components["schemas"]["ExploreTag"][];
        };
        ExploreTag: {
            name: string;
        };
        UniversityDetail: components["schemas"]["University"] & {
            faculties: components["schemas"]["FacultyWithTags"][];
        };
        UniversityDetailResponse: {
            university: components["schemas"]["UniversityDetail"];
            /** @description 自分が志望校に登録済みの学部 ID（昇順） */
            registeredFacultyIds: number[];
        };
        /** @enum {string} */
        NotificationSlot: "morning" | "evening";
        NotificationSummary: {
            date: components["schemas"]["IsoDate"];
            slot: components["schemas"]["NotificationSlot"];
            /** Format: int64 */
            eligible: number;
            /** Format: int64 */
            sent: number;
            /** Format: int64 */
            skipped: number;
            /** Format: int64 */
            failed: number;
        };
        RegistrationTracking: {
            shouldTrack: boolean;
            /**
             * @description 登録に使った方法（最初に作られたアカウント）。shouldTrack が true のときだけ
             * @enum {string}
             */
            method?: "email" | "google" | "github";
        };
        /**
         * @description 合成ユーザーの続き方の型
         * @enum {string}
         */
        SimulationCohort: "steady" | "fading" | "sporadic" | "dropped";
        SimulationUser: {
            /** Format: int64 */
            seq: number;
            email: string;
            /** @description DB の値をそのまま返す（書き込みは SimulationCohort に限っている） */
            cohort: string;
            createdAt: components["schemas"]["IsoDateTime"];
            dormantFrom: components["schemas"]["IsoDate"] | null;
            lastActedOn: components["schemas"]["IsoDate"] | null;
        };
        SimulationState: {
            /**
             * Format: int64
             * @description 次に使う連番（最後の連番＋1。だれもいなければ 1）
             */
            nextSeq: number;
            users: components["schemas"]["SimulationUser"][];
        };
        SimulationUserMark: {
            /** @description シミュレーション用のアドレス（delivered+simNNNNN@resend.dev）だけ */
            email: string;
            /** Format: int64 */
            seq: number;
            cohort: components["schemas"]["SimulationCohort"];
        };
        /** @description キーが無い項目は変えない。null なら消す */
        SimulationUserUpdate: {
            lastActedOn?: components["schemas"]["IsoDate"] | null;
            dormantFrom?: components["schemas"]["IsoDate"] | null;
        };
    };
    responses: {
        /** @description 入力が不正（文言だけ） */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 入力チェックで弾いた（文言・コード・項目） */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
        /** @description ログインしていない（またはトークンが違う） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 利用を停止されている、デモアカウントの書き込み、など */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 本文が上限（ふだんは 1MiB、CSP の報告は 16KB）を超えた */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ServerError"];
            };
        };
        /** @description 受け付けない Content-Type（受けるのは JSON・text/plain・CSP の報告の2種類。本文が無ければ無しでよい） */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ServerError"];
            };
        };
        /** @description 想定外の失敗。原因はログにだけ残す */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ServerError"];
            };
        };
    };
    parameters: {
        /** @description 期間の始まり（その日を含む） */
        From: string;
        /** @description 期間の終わり（その日を含む） */
        To: string;
    };
    requestBodies: never;
    headers: {
        /** @description JSON の SHA-1 を base64url にしたもの（Node と Go で同じ値） */
        ETag: string;
        /** @description private, no-cache */
        CacheControl: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 動いている */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 期間はサーバーが決める */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listStudyLogs: {
        parameters: {
            query?: {
                /** @description 期間の始まり（その日を含む） */
                from?: components["parameters"]["From"];
                /** @description 期間の終わり（その日を含む） */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description from を省くと直近90日、to を省くと上限なし。暦に無い日付（2026-13-45）は空の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyLog"][];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listDailyStudyMinutes: {
        parameters: {
            query?: {
                /** @description 期間の始まり（その日を含む） */
                from?: components["parameters"]["From"];
                /** @description 期間の終わり（その日を含む） */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description from を省くと直近365日 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyStudyMinutes"][];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listStudyPlans: {
        parameters: {
            query?: {
                /** @description 期間の始まり（その日を含む） */
                from?: components["parameters"]["From"];
                /** @description 期間の終わり（その日を含む） */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 省くと今日の前後90日 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyPlan"][];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 志望校の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getFirstChoiceGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 第一志望が無ければ null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirstChoiceGoal"] | null;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listTextbooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 参考書の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextbookRow"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listTextbookMasters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 参考書マスターの一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextbookMaster"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知設定 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    saveNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreference"];
            };
        };
        responses: {
            /** @description 保存した通知設定 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
            /** @description 入力チェックで弾いた（ValidationError の形）か、LINE と連携せずに LINE 通知を選んだ（Error の形） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description 更新した後の利用者 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    listUniversities: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 大学の一覧（名前順） */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreUniversity"][];
                };
            };
            /** @description 変わっていない */
            304: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getUniversity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 数字だけの正の整数（15桁まで）。形が違えば 400 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 大学詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityDetailResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    sendDailyStudyNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slot: components["schemas"]["NotificationSlot"];
                };
            };
        };
        responses: {
            /** @description 送った件数。同じ日・同じ時間帯の2回目は skipped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    trackRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 送ってよいか。初回だけ登録に使った方法も返す */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationTracking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    reportCspViolation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/csp-report": Record<string, never>;
                "application/reports+json": Record<string, never>[];
            };
        };
        responses: {
            /** @description 受け取った（中身が読めなくても同じ） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    getSimulationState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 合成ユーザー（連番の昇順） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    markSimulationUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationUserMark"];
            };
        };
        responses: {
            /** @description 付けた */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description その連番はすでに使われている */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    updateSimulationUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seq: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationUserUpdate"];
            };
        };
        responses: {
            /** @description 記録した（変える項目が無ければ、その連番が無くても 204） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    getLineConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 連携の有無 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineConnectionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    disconnectLine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解除した（連携していなくても 200） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineConnectionStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    startLineAccountLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    linkToken: string;
                };
            };
        };
        responses: {
            /** @description 画面はこの URL へ移る */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        redirectUrl: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    startLineLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LINE の同意画面、ログイン画面、または失敗を知らせるプロフィール画面へ */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    completeLineLogin: {
        parameters: {
            query?: {
                state?: string;
                code?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description プロフィール画面へ（line=connected・cancelled・invalid・expired・friend-required・already-used・failed）。 セッションが切れていれば、この URL を戻り先にしてログイン画面へ */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    receiveLineWebhook: {
        parameters: {
            query?: never;
            header: {
                "x-line-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 受け取った（イベントごとの失敗はログにだけ残す） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["BadRequest"];
        };
    };
}
