// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package main

// Defines values for NotificationSlot.
const (
	NotificationSlotEvening NotificationSlot = "evening"
	NotificationSlotMorning NotificationSlot = "morning"
)

// Valid indicates whether the value is a known member of the NotificationSlot enum.
func (e NotificationSlot) Valid() bool {
	switch e {
	case NotificationSlotEvening:
		return true
	case NotificationSlotMorning:
		return true
	default:
		return false
	}
}

// Defines values for RegistrationTrackingMethod.
const (
	SignUpMethodEmail  RegistrationTrackingMethod = "email"
	SignUpMethodGithub RegistrationTrackingMethod = "github"
	SignUpMethodGoogle RegistrationTrackingMethod = "google"
)

// Valid indicates whether the value is a known member of the RegistrationTrackingMethod enum.
func (e RegistrationTrackingMethod) Valid() bool {
	switch e {
	case SignUpMethodEmail:
		return true
	case SignUpMethodGithub:
		return true
	case SignUpMethodGoogle:
		return true
	default:
		return false
	}
}

// Defines values for ServerErrorCode.
const (
	ServerErrorCodeBodyTooLarge     ServerErrorCode = "FST_ERR_CTP_BODY_TOO_LARGE"
	ServerErrorCodeInternal         ServerErrorCode = "INTERNAL_ERROR"
	ServerErrorCodeInvalidMediaType ServerErrorCode = "FST_ERR_CTP_INVALID_MEDIA_TYPE"
	ServerErrorCodeNotFound         ServerErrorCode = "NOT_FOUND"
	ServerErrorCodeOverloaded       ServerErrorCode = "OVERLOADED"
)

// Valid indicates whether the value is a known member of the ServerErrorCode enum.
func (e ServerErrorCode) Valid() bool {
	switch e {
	case ServerErrorCodeBodyTooLarge:
		return true
	case ServerErrorCodeInternal:
		return true
	case ServerErrorCodeInvalidMediaType:
		return true
	case ServerErrorCodeNotFound:
		return true
	case ServerErrorCodeOverloaded:
		return true
	default:
		return false
	}
}

// Defines values for SimulationCohort.
const (
	SimulationCohortDropped  SimulationCohort = "dropped"
	SimulationCohortFading   SimulationCohort = "fading"
	SimulationCohortSporadic SimulationCohort = "sporadic"
	SimulationCohortSteady   SimulationCohort = "steady"
)

// Valid indicates whether the value is a known member of the SimulationCohort enum.
func (e SimulationCohort) Valid() bool {
	switch e {
	case SimulationCohortDropped:
		return true
	case SimulationCohortFading:
		return true
	case SimulationCohortSporadic:
		return true
	case SimulationCohortSteady:
		return true
	default:
		return false
	}
}

// Defines values for GetHealth200JSONResponseBodyOk.
const (
	True GetHealth200JSONResponseBodyOk = true
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyOk enum.
func (e GetHealth200JSONResponseBodyOk) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// DailyStudyMinutes defines model for DailyStudyMinutes.
type DailyStudyMinutes struct {
	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date    IsoDateTime `json:"date"`
	Minutes int64       `json:"minutes"`
}

// Dashboard defines model for Dashboard.
type Dashboard struct {
	DailyMinutes []DailyStudyMinutes `json:"dailyMinutes"`

	// LogRange 両端を含む期間（"YYYY-MM-DD"）
	LogRange DateRange  `json:"logRange"`
	Logs     []StudyLog `json:"logs"`

	// Month 今日の月（"YYYY-MM"）
	Month string `json:"month"`

	// PlanRange 両端を含む期間（"YYYY-MM-DD"）
	PlanRange DateRange   `json:"planRange"`
	Plans     []StudyPlan `json:"plans"`
}

// DateRange 両端を含む期間（"YYYY-MM-DD"）
type DateRange struct {
	// From 日付だけ（"YYYY-MM-DD"、日本時間の日付）
	From IsoDate `json:"from"`

	// To 日付だけ（"YYYY-MM-DD"、日本時間の日付）
	To IsoDate `json:"to"`
}

// Error ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type Error struct {
	Error string `json:"error"`
}

// ExploreFaculty defines model for ExploreFaculty.
type ExploreFaculty struct {
	Tags []ExploreTag `json:"tags"`
}

// ExploreTag defines model for ExploreTag.
type ExploreTag struct {
	Name string `json:"name"`
}

// ExploreUniversity 大学を探す画面の1件。画面が使うのは大学の列と学部ごとのタグ名だけ。 Go はこの形を手書きの型で返す（JSON のキーの順番を Node と同じにして ETag をそろえるため）
type ExploreUniversity struct {
	Faculties  []ExploreFaculty `json:"faculties"`
	ID         int64            `json:"id"`
	Name       string           `json:"name"`
	Prefecture string           `json:"prefecture"`
	Type       string           `json:"type"`
}

// Faculty 学部（大学を入れ子にしない）
type Faculty struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// ExamDate Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	ExamDate     IsoDateTime `json:"examDate"`
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	UniversityID int64       `json:"universityId"`
}

// FacultyWithTags defines model for FacultyWithTags.
type FacultyWithTags struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// ExamDate Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	ExamDate     IsoDateTime `json:"examDate"`
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Tags         []Tag       `json:"tags"`
	UniversityID int64       `json:"universityId"`
}

// FacultyWithUniversity defines model for FacultyWithUniversity.
type FacultyWithUniversity struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// ExamDate Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	ExamDate     IsoDateTime `json:"examDate"`
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	University   University  `json:"university"`
	UniversityID int64       `json:"universityId"`
}

// FacultyWithUniversityAndTags defines model for FacultyWithUniversityAndTags.
type FacultyWithUniversityAndTags struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// ExamDate Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	ExamDate     IsoDateTime `json:"examDate"`
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Tags         []Tag       `json:"tags"`
	University   University  `json:"university"`
	UniversityID int64       `json:"universityId"`
}

// FirstChoiceGoal 第一志望。学部・大学つき（タグは付けない）
type FirstChoiceGoal struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt     IsoDateTime           `json:"createdAt"`
	Faculty       FacultyWithUniversity `json:"faculty"`
	FacultyID     int64                 `json:"facultyId"`
	ID            int64                 `json:"id"`
	IsFirstChoice bool                  `json:"isFirstChoice"`
	Note          *string               `json:"note"`
	Status        string                `json:"status"`
	UserID        string                `json:"userId"`
}

// Goal 志望校の一覧の1件。学部・大学・学部のタグつき
type Goal struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt     IsoDateTime                  `json:"createdAt"`
	Faculty       FacultyWithUniversityAndTags `json:"faculty"`
	FacultyID     int64                        `json:"facultyId"`
	ID            int64                        `json:"id"`
	IsFirstChoice bool                         `json:"isFirstChoice"`
	Note          *string                      `json:"note"`
	Status        string                       `json:"status"`
	UserID        string                       `json:"userId"`
}

// GoalFields 志望校の列（学部は含まない）
type GoalFields struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt     IsoDateTime `json:"createdAt"`
	FacultyID     int64       `json:"facultyId"`
	ID            int64       `json:"id"`
	IsFirstChoice bool        `json:"isFirstChoice"`
	Note          *string     `json:"note"`
	Status        string      `json:"status"`
	UserID        string      `json:"userId"`
}

// IsoDate 日付だけ（"YYYY-MM-DD"、日本時間の日付）
type IsoDate = string

// IsoDateTime Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
type IsoDateTime = string

// NotificationPreference defines model for NotificationPreference.
type NotificationPreference struct {
	EmailEveningEnabled bool `json:"emailEveningEnabled"`
	EmailMorningEnabled bool `json:"emailMorningEnabled"`
	LineEveningEnabled  bool `json:"lineEveningEnabled"`
	LineMorningEnabled  bool `json:"lineMorningEnabled"`
}

// NotificationSlot defines model for NotificationSlot.
type NotificationSlot string

// NotificationSummary defines model for NotificationSummary.
type NotificationSummary struct {
	// Date 日付だけ（"YYYY-MM-DD"、日本時間の日付）
	Date     IsoDate          `json:"date"`
	Eligible int64            `json:"eligible"`
	Failed   int64            `json:"failed"`
	Sent     int64            `json:"sent"`
	Skipped  int64            `json:"skipped"`
	Slot     NotificationSlot `json:"slot"`
}

// RegistrationTracking defines model for RegistrationTracking.
type RegistrationTracking struct {
	// Method 登録に使った方法（最初に作られたアカウント）。shouldTrack が true のときだけ
	Method      *RegistrationTrackingMethod `json:"method,omitempty"`
	ShouldTrack bool                        `json:"shouldTrack"`
}

// RegistrationTrackingMethod 登録に使った方法（最初に作られたアカウント）。shouldTrack が true のときだけ
type RegistrationTrackingMethod string

// ServerError 想定外の失敗・混雑・存在しないパス
type ServerError struct {
	Code  ServerErrorCode `json:"code"`
	Error string          `json:"error"`
	ReqID string          `json:"reqId"`
}

// ServerErrorCode defines model for ServerError.Code.
type ServerErrorCode string

// SimulationCohort 合成ユーザーの続き方の型
type SimulationCohort string

// SimulationState defines model for SimulationState.
type SimulationState struct {
	// NextSeq 次に使う連番（最後の連番＋1。だれもいなければ 1）
	NextSeq int64            `json:"nextSeq"`
	Users   []SimulationUser `json:"users"`
}

// SimulationUser defines model for SimulationUser.
type SimulationUser struct {
	// Cohort DB の値をそのまま返す（書き込みは SimulationCohort に限っている）
	Cohort string `json:"cohort"`

	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt   IsoDateTime `json:"createdAt"`
	DormantFrom *IsoDate    `json:"dormantFrom"`
	Email       string      `json:"email"`
	LastActedOn *IsoDate    `json:"lastActedOn"`
	Seq         int64       `json:"seq"`
}

// SimulationUserMark defines model for SimulationUserMark.
type SimulationUserMark struct {
	// Cohort 合成ユーザーの続き方の型
	Cohort SimulationCohort `json:"cohort"`

	// Email シミュレーション用のアドレス（delivered+simNNNNN@resend.dev）だけ
	Email string `json:"email"`
	Seq   int64  `json:"seq"`
}

// SimulationUserUpdate キーが無い項目は変えない。null なら消す
type SimulationUserUpdate struct {
	DormantFrom *IsoDate `json:"dormantFrom,omitempty"`
	LastActedOn *IsoDate `json:"lastActedOn,omitempty"`
}

// StudyLog defines model for StudyLog.
type StudyLog struct {
	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date        IsoDateTime `json:"date"`
	ID          int64       `json:"id"`
	Memo        *string     `json:"memo"`
	Minutes     int64       `json:"minutes"`
	RangeEnd    *int64      `json:"rangeEnd"`
	RangeStart  *int64      `json:"rangeStart"`
	RangeUnit   *string     `json:"rangeUnit"`
	StudyPlanID *int64      `json:"studyPlanId"`
	Subject     *string     `json:"subject"`
	Textbook    *Textbook   `json:"textbook"`
	TextbookID  *int64      `json:"textbookId"`
}

// StudyPlan defines model for StudyPlan.
type StudyPlan struct {
	Content *string `json:"content"`

	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date       IsoDateTime `json:"date"`
	Done       bool        `json:"done"`
	ID         int64       `json:"id"`
	RangeEnd   *int64      `json:"rangeEnd"`
	RangeStart *int64      `json:"rangeStart"`
	RangeUnit  *string     `json:"rangeUnit"`
	StudyLogID *int64      `json:"studyLogId"`
	Subject    *string     `json:"subject"`
	Textbook   *Textbook   `json:"textbook"`
	TextbookID *int64      `json:"textbookId"`
}

// Tag defines model for Tag.
type Tag struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
}

// Textbook 実績・予定に JOIN した参考書（表示用）
type Textbook struct {
	ID          int64        `json:"id"`
	MasterID    *int64       `json:"masterId"`
	Name        string       `json:"name"`
	RangeUnit   *string      `json:"rangeUnit"`
	Subject     *string      `json:"subject"`
	TargetDate  *IsoDateTime `json:"targetDate"`
	TotalAmount *int64       `json:"totalAmount"`
}

// TextbookMaster defines model for TextbookMaster.
type TextbookMaster struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`
	Edition   *string     `json:"edition"`
	ID        int64       `json:"id"`
	ISBN      string      `json:"isbn"`

	// Metrics 総量の候補（id 順）。無くても []
	Metrics   []TextbookMasterMetric `json:"metrics"`
	Name      string                 `json:"name"`
	Publisher *string                `json:"publisher"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
}

// TextbookMasterMetric defines model for TextbookMasterMetric.
type TextbookMasterMetric struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt   IsoDateTime `json:"createdAt"`
	ID          int64       `json:"id"`
	IsDefault   bool        `json:"isDefault"`
	MasterID    int64       `json:"masterId"`
	TotalAmount int64       `json:"totalAmount"`
	Unit        string      `json:"unit"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
}

// TextbookRow 自分の参考書（DB の行そのまま）
type TextbookRow struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt   IsoDateTime  `json:"createdAt"`
	ID          int64        `json:"id"`
	MasterID    *int64       `json:"masterId"`
	Name        string       `json:"name"`
	RangeUnit   *string      `json:"rangeUnit"`
	Subject     *string      `json:"subject"`
	TargetDate  *IsoDateTime `json:"targetDate"`
	TotalAmount *int64       `json:"totalAmount"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
	UserID    string      `json:"userId"`
}

// University defines model for University.
type University struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt  IsoDateTime `json:"createdAt"`
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Prefecture string      `json:"prefecture"`
	Type       string      `json:"type"`
}

// UniversityDetail defines model for UniversityDetail.
type UniversityDetail struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt  IsoDateTime       `json:"createdAt"`
	Faculties  []FacultyWithTags `json:"faculties"`
	ID         int64             `json:"id"`
	Name       string            `json:"name"`
	Prefecture string            `json:"prefecture"`
	Type       string            `json:"type"`
}

// UniversityDetailResponse defines model for UniversityDetailResponse.
type UniversityDetailResponse struct {
	// RegisteredFacultyIds 自分が志望校に登録済みの学部 ID（昇順）
	RegisteredFacultyIds []int64          `json:"registeredFacultyIds"`
	University           UniversityDetail `json:"university"`
}

// ValidationError 入力チェックで弾いたときのエラー（Node の routes/validation-error.ts、Go の query.go）
type ValidationError struct {
	// Code 種類。自分で書いた規則は名前（range_end_before_start など）、 組み込みのチェックは Zod の code（too_small・invalid_type・invalid_format など）
	Code string `json:"code"`

	// Error 画面にそのまま出す文言
	Error string `json:"error"`

	// Field どの項目か（"rangeEnd"・"items.0.unit"）。項目に結びつかなければ null
	Field *string `json:"field"`
}

// From defines model for From.
type From = string

// To defines model for To.
type To = string

// BadRequest ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type BadRequest = Error

// Forbidden ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type Forbidden = Error

// InternalError 想定外の失敗・混雑・存在しないパス
type InternalError = ServerError

// NotFound ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type NotFound = Error

// PayloadTooLarge 想定外の失敗・混雑・存在しないパス
type PayloadTooLarge = ServerError

// Unauthorized ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type Unauthorized = Error

// UnsupportedMediaType 想定外の失敗・混雑・存在しないパス
type UnsupportedMediaType = ServerError

// SendDailyStudyNotificationsJSONBody defines parameters for SendDailyStudyNotifications.
type SendDailyStudyNotificationsJSONBody struct {
	Slot NotificationSlot `json:"slot"`
}

// ReportCspViolationApplicationReportsPlusJSONBody defines parameters for ReportCspViolation.
type ReportCspViolationApplicationReportsPlusJSONBody = []map[string]interface{}

// GetHealth200JSONResponseBodyOk defines parameters for GetHealth.
type GetHealth200JSONResponseBodyOk bool

// ListStudyLogsParams defines parameters for ListStudyLogs.
type ListStudyLogsParams struct {
	// From 期間の始まり（その日を含む）
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To 期間の終わり（その日を含む）
	To *To `form:"to,omitempty" json:"to,omitempty"`
}

// ListDailyStudyMinutesParams defines parameters for ListDailyStudyMinutes.
type ListDailyStudyMinutesParams struct {
	// From 期間の始まり（その日を含む）
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To 期間の終わり（その日を含む）
	To *To `form:"to,omitempty" json:"to,omitempty"`
}

// ListStudyPlansParams defines parameters for ListStudyPlans.
type ListStudyPlansParams struct {
	// From 期間の始まり（その日を含む）
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To 期間の終わり（その日を含む）
	To *To `form:"to,omitempty" json:"to,omitempty"`
}

// ListUniversitiesParams defines parameters for ListUniversities.
type ListUniversitiesParams struct {
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// SendDailyStudyNotificationsJSONRequestBody defines body for SendDailyStudyNotifications for application/json ContentType.
type SendDailyStudyNotificationsJSONRequestBody SendDailyStudyNotificationsJSONBody

// ReportCspViolationApplicationReportsPlusJSONRequestBody defines body for ReportCspViolation for application/reports+json ContentType.
type ReportCspViolationApplicationReportsPlusJSONRequestBody = ReportCspViolationApplicationReportsPlusJSONBody

// MarkSimulationUserJSONRequestBody defines body for MarkSimulationUser for application/json ContentType.
type MarkSimulationUserJSONRequestBody = SimulationUserMark

// UpdateSimulationUserJSONRequestBody defines body for UpdateSimulationUser for application/json ContentType.
type UpdateSimulationUserJSONRequestBody = SimulationUserUpdate
