name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Lint
        run: npx eslint --max-warnings 0

      - name: Type check
        run: npx tsc --noEmit
      
      - name: Test
        run: npm test

      - name: Build
        run: npx next build
        env:
            MICROCMS_SERVICE_DOMAIN: dummy
            MICROCMS_API_KEY: dummy
            DATABASE_URL: mysql://u:p@localhost:3306/db
            BETTER_AUTH_SECRET: ecPTNJXeffEkIMhtDiAKQI8X/dv0xZ5PWupA15w9rVU=
            BETTER_AUTH_URL: http://localhost:3000
