// Package apischema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apischema

// Defines values for AdminUserRole.
const (
	AdminUserRoleAdmin AdminUserRole = "admin"
	AdminUserRoleUser  AdminUserRole = "user"
)

// Valid indicates whether the value is a known member of the AdminUserRole enum.
func (e AdminUserRole) Valid() bool {
	switch e {
	case AdminUserRoleAdmin:
		return true
	case AdminUserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for CompleteStudyPlanInputRangeUnit.
const (
	CompleteStudyPlanInputRangeUnitChapter  CompleteStudyPlanInputRangeUnit = "chapter"
	CompleteStudyPlanInputRangeUnitNumber   CompleteStudyPlanInputRangeUnit = "number"
	CompleteStudyPlanInputRangeUnitPage     CompleteStudyPlanInputRangeUnit = "page"
	CompleteStudyPlanInputRangeUnitPart     CompleteStudyPlanInputRangeUnit = "part"
	CompleteStudyPlanInputRangeUnitQuestion CompleteStudyPlanInputRangeUnit = "question"
	CompleteStudyPlanInputRangeUnitSection  CompleteStudyPlanInputRangeUnit = "section"
)

// Valid indicates whether the value is a known member of the CompleteStudyPlanInputRangeUnit enum.
func (e CompleteStudyPlanInputRangeUnit) Valid() bool {
	switch e {
	case CompleteStudyPlanInputRangeUnitChapter:
		return true
	case CompleteStudyPlanInputRangeUnitNumber:
		return true
	case CompleteStudyPlanInputRangeUnitPage:
		return true
	case CompleteStudyPlanInputRangeUnitPart:
		return true
	case CompleteStudyPlanInputRangeUnitQuestion:
		return true
	case CompleteStudyPlanInputRangeUnitSection:
		return true
	default:
		return false
	}
}

// Defines values for DeletedMessage.
const (
	DeletedMessageDeleted DeletedMessage = "Deleted"
)

// Valid indicates whether the value is a known member of the DeletedMessage enum.
func (e DeletedMessage) Valid() bool {
	switch e {
	case DeletedMessageDeleted:
		return true
	default:
		return false
	}
}

// Defines values for GoalInputStatus.
const (
	GoalInputStatusCandidate GoalInputStatus = "candidate"
	GoalInputStatusDecided   GoalInputStatus = "decided"
)

// Valid indicates whether the value is a known member of the GoalInputStatus enum.
func (e GoalInputStatus) Valid() bool {
	switch e {
	case GoalInputStatusCandidate:
		return true
	case GoalInputStatusDecided:
		return true
	default:
		return false
	}
}

// Defines values for GoalPatchInputStatus.
const (
	GoalPatchInputStatusCandidate GoalPatchInputStatus = "candidate"
	GoalPatchInputStatusDecided   GoalPatchInputStatus = "decided"
)

// Valid indicates whether the value is a known member of the GoalPatchInputStatus enum.
func (e GoalPatchInputStatus) Valid() bool {
	switch e {
	case GoalPatchInputStatusCandidate:
		return true
	case GoalPatchInputStatusDecided:
		return true
	default:
		return false
	}
}

// Defines values for GoalUpdateInputStatus.
const (
	GoalUpdateInputStatusCandidate GoalUpdateInputStatus = "candidate"
	GoalUpdateInputStatusDecided   GoalUpdateInputStatus = "decided"
)

// Valid indicates whether the value is a known member of the GoalUpdateInputStatus enum.
func (e GoalUpdateInputStatus) Valid() bool {
	switch e {
	case GoalUpdateInputStatusCandidate:
		return true
	case GoalUpdateInputStatusDecided:
		return true
	default:
		return false
	}
}

// Defines values for NotificationSlot.
const (
	NotificationSlotEvening NotificationSlot = "evening"
	NotificationSlotMorning NotificationSlot = "morning"
)

// Valid indicates whether the value is a known member of the NotificationSlot enum.
func (e NotificationSlot) Valid() bool {
	switch e {
	case NotificationSlotEvening:
		return true
	case NotificationSlotMorning:
		return true
	default:
		return false
	}
}

// Defines values for OkMessageMessage.
const (
	OkMessageOK OkMessageMessage = "OK"
)

// Valid indicates whether the value is a known member of the OkMessageMessage enum.
func (e OkMessageMessage) Valid() bool {
	switch e {
	case OkMessageOK:
		return true
	default:
		return false
	}
}

// Defines values for RegistrationTrackingMethod.
const (
	SignUpMethodEmail  RegistrationTrackingMethod = "email"
	SignUpMethodGithub RegistrationTrackingMethod = "github"
	SignUpMethodGoogle RegistrationTrackingMethod = "google"
)

// Valid indicates whether the value is a known member of the RegistrationTrackingMethod enum.
func (e RegistrationTrackingMethod) Valid() bool {
	switch e {
	case SignUpMethodEmail:
		return true
	case SignUpMethodGithub:
		return true
	case SignUpMethodGoogle:
		return true
	default:
		return false
	}
}

// Defines values for ServerErrorCode.
const (
	ServerErrorCodeBodyTooLarge         ServerErrorCode = "FST_ERR_CTP_BODY_TOO_LARGE"
	ServerErrorCodeInternal             ServerErrorCode = "INTERNAL_ERROR"
	ServerErrorCodeInvalidContentLength ServerErrorCode = "FST_ERR_CTP_INVALID_CONTENT_LENGTH"
	ServerErrorCodeInvalidMediaType     ServerErrorCode = "FST_ERR_CTP_INVALID_MEDIA_TYPE"
	ServerErrorCodeNotFound             ServerErrorCode = "NOT_FOUND"
	ServerErrorCodeOverloaded           ServerErrorCode = "OVERLOADED"
	ServerErrorCodeTooManyRequests      ServerErrorCode = "TOO_MANY_REQUESTS"
)

// Valid indicates whether the value is a known member of the ServerErrorCode enum.
func (e ServerErrorCode) Valid() bool {
	switch e {
	case ServerErrorCodeBodyTooLarge:
		return true
	case ServerErrorCodeInternal:
		return true
	case ServerErrorCodeInvalidContentLength:
		return true
	case ServerErrorCodeInvalidMediaType:
		return true
	case ServerErrorCodeNotFound:
		return true
	case ServerErrorCodeOverloaded:
		return true
	case ServerErrorCodeTooManyRequests:
		return true
	default:
		return false
	}
}

// Defines values for SimulationCohort.
const (
	SimulationCohortDropped  SimulationCohort = "dropped"
	SimulationCohortFading   SimulationCohort = "fading"
	SimulationCohortSporadic SimulationCohort = "sporadic"
	SimulationCohortSteady   SimulationCohort = "steady"
)

// Valid indicates whether the value is a known member of the SimulationCohort enum.
func (e SimulationCohort) Valid() bool {
	switch e {
	case SimulationCohortDropped:
		return true
	case SimulationCohortFading:
		return true
	case SimulationCohortSporadic:
		return true
	case SimulationCohortSteady:
		return true
	default:
		return false
	}
}

// Defines values for StudyLogInputRangeUnit.
const (
	StudyLogInputRangeUnitChapter  StudyLogInputRangeUnit = "chapter"
	StudyLogInputRangeUnitNumber   StudyLogInputRangeUnit = "number"
	StudyLogInputRangeUnitPage     StudyLogInputRangeUnit = "page"
	StudyLogInputRangeUnitPart     StudyLogInputRangeUnit = "part"
	StudyLogInputRangeUnitQuestion StudyLogInputRangeUnit = "question"
	StudyLogInputRangeUnitSection  StudyLogInputRangeUnit = "section"
)

// Valid indicates whether the value is a known member of the StudyLogInputRangeUnit enum.
func (e StudyLogInputRangeUnit) Valid() bool {
	switch e {
	case StudyLogInputRangeUnitChapter:
		return true
	case StudyLogInputRangeUnitNumber:
		return true
	case StudyLogInputRangeUnitPage:
		return true
	case StudyLogInputRangeUnitPart:
		return true
	case StudyLogInputRangeUnitQuestion:
		return true
	case StudyLogInputRangeUnitSection:
		return true
	default:
		return false
	}
}

// Defines values for StudyLogInputSubject.
const (
	StudyLogInputSubjectEnglish  StudyLogInputSubject = "english"
	StudyLogInputSubjectJapanese StudyLogInputSubject = "japanese"
	StudyLogInputSubjectMath     StudyLogInputSubject = "math"
	StudyLogInputSubjectOther    StudyLogInputSubject = "other"
	StudyLogInputSubjectScience  StudyLogInputSubject = "science"
	StudyLogInputSubjectSocial   StudyLogInputSubject = "social"
)

// Valid indicates whether the value is a known member of the StudyLogInputSubject enum.
func (e StudyLogInputSubject) Valid() bool {
	switch e {
	case StudyLogInputSubjectEnglish:
		return true
	case StudyLogInputSubjectJapanese:
		return true
	case StudyLogInputSubjectMath:
		return true
	case StudyLogInputSubjectOther:
		return true
	case StudyLogInputSubjectScience:
		return true
	case StudyLogInputSubjectSocial:
		return true
	default:
		return false
	}
}

// Defines values for StudyPlanItemInputRangeUnit.
const (
	StudyPlanItemInputRangeUnitChapter  StudyPlanItemInputRangeUnit = "chapter"
	StudyPlanItemInputRangeUnitNumber   StudyPlanItemInputRangeUnit = "number"
	StudyPlanItemInputRangeUnitPage     StudyPlanItemInputRangeUnit = "page"
	StudyPlanItemInputRangeUnitPart     StudyPlanItemInputRangeUnit = "part"
	StudyPlanItemInputRangeUnitQuestion StudyPlanItemInputRangeUnit = "question"
	StudyPlanItemInputRangeUnitSection  StudyPlanItemInputRangeUnit = "section"
)

// Valid indicates whether the value is a known member of the StudyPlanItemInputRangeUnit enum.
func (e StudyPlanItemInputRangeUnit) Valid() bool {
	switch e {
	case StudyPlanItemInputRangeUnitChapter:
		return true
	case StudyPlanItemInputRangeUnitNumber:
		return true
	case StudyPlanItemInputRangeUnitPage:
		return true
	case StudyPlanItemInputRangeUnitPart:
		return true
	case StudyPlanItemInputRangeUnitQuestion:
		return true
	case StudyPlanItemInputRangeUnitSection:
		return true
	default:
		return false
	}
}

// Defines values for StudyPlanItemInputSubject.
const (
	StudyPlanItemInputSubjectEnglish  StudyPlanItemInputSubject = "english"
	StudyPlanItemInputSubjectJapanese StudyPlanItemInputSubject = "japanese"
	StudyPlanItemInputSubjectMath     StudyPlanItemInputSubject = "math"
	StudyPlanItemInputSubjectOther    StudyPlanItemInputSubject = "other"
	StudyPlanItemInputSubjectScience  StudyPlanItemInputSubject = "science"
	StudyPlanItemInputSubjectSocial   StudyPlanItemInputSubject = "social"
)

// Valid indicates whether the value is a known member of the StudyPlanItemInputSubject enum.
func (e StudyPlanItemInputSubject) Valid() bool {
	switch e {
	case StudyPlanItemInputSubjectEnglish:
		return true
	case StudyPlanItemInputSubjectJapanese:
		return true
	case StudyPlanItemInputSubjectMath:
		return true
	case StudyPlanItemInputSubjectOther:
		return true
	case StudyPlanItemInputSubjectScience:
		return true
	case StudyPlanItemInputSubjectSocial:
		return true
	default:
		return false
	}
}

// Defines values for StudyPlanUpdateInputRangeUnit.
const (
	StudyPlanUpdateInputRangeUnitChapter  StudyPlanUpdateInputRangeUnit = "chapter"
	StudyPlanUpdateInputRangeUnitNumber   StudyPlanUpdateInputRangeUnit = "number"
	StudyPlanUpdateInputRangeUnitPage     StudyPlanUpdateInputRangeUnit = "page"
	StudyPlanUpdateInputRangeUnitPart     StudyPlanUpdateInputRangeUnit = "part"
	StudyPlanUpdateInputRangeUnitQuestion StudyPlanUpdateInputRangeUnit = "question"
	StudyPlanUpdateInputRangeUnitSection  StudyPlanUpdateInputRangeUnit = "section"
)

// Valid indicates whether the value is a known member of the StudyPlanUpdateInputRangeUnit enum.
func (e StudyPlanUpdateInputRangeUnit) Valid() bool {
	switch e {
	case StudyPlanUpdateInputRangeUnitChapter:
		return true
	case StudyPlanUpdateInputRangeUnitNumber:
		return true
	case StudyPlanUpdateInputRangeUnitPage:
		return true
	case StudyPlanUpdateInputRangeUnitPart:
		return true
	case StudyPlanUpdateInputRangeUnitQuestion:
		return true
	case StudyPlanUpdateInputRangeUnitSection:
		return true
	default:
		return false
	}
}

// Defines values for StudyPlanUpdateInputSubject.
const (
	StudyPlanUpdateInputSubjectEnglish  StudyPlanUpdateInputSubject = "english"
	StudyPlanUpdateInputSubjectJapanese StudyPlanUpdateInputSubject = "japanese"
	StudyPlanUpdateInputSubjectMath     StudyPlanUpdateInputSubject = "math"
	StudyPlanUpdateInputSubjectOther    StudyPlanUpdateInputSubject = "other"
	StudyPlanUpdateInputSubjectScience  StudyPlanUpdateInputSubject = "science"
	StudyPlanUpdateInputSubjectSocial   StudyPlanUpdateInputSubject = "social"
)

// Valid indicates whether the value is a known member of the StudyPlanUpdateInputSubject enum.
func (e StudyPlanUpdateInputSubject) Valid() bool {
	switch e {
	case StudyPlanUpdateInputSubjectEnglish:
		return true
	case StudyPlanUpdateInputSubjectJapanese:
		return true
	case StudyPlanUpdateInputSubjectMath:
		return true
	case StudyPlanUpdateInputSubjectOther:
		return true
	case StudyPlanUpdateInputSubjectScience:
		return true
	case StudyPlanUpdateInputSubjectSocial:
		return true
	default:
		return false
	}
}

// Defines values for TextbookMasterInputMetricsUnit.
const (
	TextbookMasterInputMetricsUnitChapter  TextbookMasterInputMetricsUnit = "chapter"
	TextbookMasterInputMetricsUnitNumber   TextbookMasterInputMetricsUnit = "number"
	TextbookMasterInputMetricsUnitPage     TextbookMasterInputMetricsUnit = "page"
	TextbookMasterInputMetricsUnitPart     TextbookMasterInputMetricsUnit = "part"
	TextbookMasterInputMetricsUnitQuestion TextbookMasterInputMetricsUnit = "question"
	TextbookMasterInputMetricsUnitSection  TextbookMasterInputMetricsUnit = "section"
)

// Valid indicates whether the value is a known member of the TextbookMasterInputMetricsUnit enum.
func (e TextbookMasterInputMetricsUnit) Valid() bool {
	switch e {
	case TextbookMasterInputMetricsUnitChapter:
		return true
	case TextbookMasterInputMetricsUnitNumber:
		return true
	case TextbookMasterInputMetricsUnitPage:
		return true
	case TextbookMasterInputMetricsUnitPart:
		return true
	case TextbookMasterInputMetricsUnitQuestion:
		return true
	case TextbookMasterInputMetricsUnitSection:
		return true
	default:
		return false
	}
}

// Defines values for TextbookNameInputRangeUnit.
const (
	TextbookNameInputRangeUnitChapter  TextbookNameInputRangeUnit = "chapter"
	TextbookNameInputRangeUnitNumber   TextbookNameInputRangeUnit = "number"
	TextbookNameInputRangeUnitPage     TextbookNameInputRangeUnit = "page"
	TextbookNameInputRangeUnitPart     TextbookNameInputRangeUnit = "part"
	TextbookNameInputRangeUnitQuestion TextbookNameInputRangeUnit = "question"
	TextbookNameInputRangeUnitSection  TextbookNameInputRangeUnit = "section"
)

// Valid indicates whether the value is a known member of the TextbookNameInputRangeUnit enum.
func (e TextbookNameInputRangeUnit) Valid() bool {
	switch e {
	case TextbookNameInputRangeUnitChapter:
		return true
	case TextbookNameInputRangeUnitNumber:
		return true
	case TextbookNameInputRangeUnitPage:
		return true
	case TextbookNameInputRangeUnitPart:
		return true
	case TextbookNameInputRangeUnitQuestion:
		return true
	case TextbookNameInputRangeUnitSection:
		return true
	default:
		return false
	}
}

// Defines values for TextbookNameInputSubject.
const (
	TextbookNameInputSubjectEnglish  TextbookNameInputSubject = "english"
	TextbookNameInputSubjectJapanese TextbookNameInputSubject = "japanese"
	TextbookNameInputSubjectMath     TextbookNameInputSubject = "math"
	TextbookNameInputSubjectOther    TextbookNameInputSubject = "other"
	TextbookNameInputSubjectScience  TextbookNameInputSubject = "science"
	TextbookNameInputSubjectSocial   TextbookNameInputSubject = "social"
)

// Valid indicates whether the value is a known member of the TextbookNameInputSubject enum.
func (e TextbookNameInputSubject) Valid() bool {
	switch e {
	case TextbookNameInputSubjectEnglish:
		return true
	case TextbookNameInputSubjectJapanese:
		return true
	case TextbookNameInputSubjectMath:
		return true
	case TextbookNameInputSubjectOther:
		return true
	case TextbookNameInputSubjectScience:
		return true
	case TextbookNameInputSubjectSocial:
		return true
	default:
		return false
	}
}

// Defines values for TextbookProgressInputRangeUnit.
const (
	TextbookProgressInputRangeUnitChapter  TextbookProgressInputRangeUnit = "chapter"
	TextbookProgressInputRangeUnitNumber   TextbookProgressInputRangeUnit = "number"
	TextbookProgressInputRangeUnitPage     TextbookProgressInputRangeUnit = "page"
	TextbookProgressInputRangeUnitPart     TextbookProgressInputRangeUnit = "part"
	TextbookProgressInputRangeUnitQuestion TextbookProgressInputRangeUnit = "question"
	TextbookProgressInputRangeUnitSection  TextbookProgressInputRangeUnit = "section"
)

// Valid indicates whether the value is a known member of the TextbookProgressInputRangeUnit enum.
func (e TextbookProgressInputRangeUnit) Valid() bool {
	switch e {
	case TextbookProgressInputRangeUnitChapter:
		return true
	case TextbookProgressInputRangeUnitNumber:
		return true
	case TextbookProgressInputRangeUnitPage:
		return true
	case TextbookProgressInputRangeUnitPart:
		return true
	case TextbookProgressInputRangeUnitQuestion:
		return true
	case TextbookProgressInputRangeUnitSection:
		return true
	default:
		return false
	}
}

// Defines values for TextbookProgressInputSubject.
const (
	TextbookProgressInputSubjectEnglish  TextbookProgressInputSubject = "english"
	TextbookProgressInputSubjectJapanese TextbookProgressInputSubject = "japanese"
	TextbookProgressInputSubjectMath     TextbookProgressInputSubject = "math"
	TextbookProgressInputSubjectOther    TextbookProgressInputSubject = "other"
	TextbookProgressInputSubjectScience  TextbookProgressInputSubject = "science"
	TextbookProgressInputSubjectSocial   TextbookProgressInputSubject = "social"
)

// Valid indicates whether the value is a known member of the TextbookProgressInputSubject enum.
func (e TextbookProgressInputSubject) Valid() bool {
	switch e {
	case TextbookProgressInputSubjectEnglish:
		return true
	case TextbookProgressInputSubjectJapanese:
		return true
	case TextbookProgressInputSubjectMath:
		return true
	case TextbookProgressInputSubjectOther:
		return true
	case TextbookProgressInputSubjectScience:
		return true
	case TextbookProgressInputSubjectSocial:
		return true
	default:
		return false
	}
}

// Defines values for UniversityInputType.
const (
	UniversityTypeNational UniversityInputType = "国立"
	UniversityTypePrivate  UniversityInputType = "私立"
	UniversityTypePublic   UniversityInputType = "公立"
)

// Valid indicates whether the value is a known member of the UniversityInputType enum.
func (e UniversityInputType) Valid() bool {
	switch e {
	case UniversityTypeNational:
		return true
	case UniversityTypePrivate:
		return true
	case UniversityTypePublic:
		return true
	default:
		return false
	}
}

// Defines values for UserKind.
const (
	UserKindDemo UserKind = "demo"
	UserKindReal UserKind = "real"
	UserKindSeed UserKind = "seed"
	UserKindSim  UserKind = "sim"
)

// Valid indicates whether the value is a known member of the UserKind enum.
func (e UserKind) Valid() bool {
	switch e {
	case UserKindDemo:
		return true
	case UserKindReal:
		return true
	case UserKindSeed:
		return true
	case UserKindSim:
		return true
	default:
		return false
	}
}

// Defines values for GetHealth200JSONResponseBodyOk.
const (
	GetHealth200JSONResponseBodyOkTrue GetHealth200JSONResponseBodyOk = true
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyOk enum.
func (e GetHealth200JSONResponseBodyOk) Valid() bool {
	switch e {
	case GetHealth200JSONResponseBodyOkTrue:
		return true
	default:
		return false
	}
}

// Defines values for ReceiveLineWebhook200JSONResponseBodyOk.
const (
	ReceiveLineWebhook200JSONResponseBodyOkTrue ReceiveLineWebhook200JSONResponseBodyOk = true
)

// Valid indicates whether the value is a known member of the ReceiveLineWebhook200JSONResponseBodyOk enum.
func (e ReceiveLineWebhook200JSONResponseBodyOk) Valid() bool {
	switch e {
	case ReceiveLineWebhook200JSONResponseBodyOkTrue:
		return true
	default:
		return false
	}
}

// Defines values for ReceiveMicrocmsWebhook200JSONResponseBodyDeploy.
const (
	Dispatched ReceiveMicrocmsWebhook200JSONResponseBodyDeploy = "dispatched"
	Queued     ReceiveMicrocmsWebhook200JSONResponseBodyDeploy = "queued"
	Skipped    ReceiveMicrocmsWebhook200JSONResponseBodyDeploy = "skipped"
)

// Valid indicates whether the value is a known member of the ReceiveMicrocmsWebhook200JSONResponseBodyDeploy enum.
func (e ReceiveMicrocmsWebhook200JSONResponseBodyDeploy) Valid() bool {
	switch e {
	case Dispatched:
		return true
	case Queued:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// AdminBanResult defines model for AdminBanResult.
type AdminBanResult struct {
	// BannedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	BannedAt IsoDateTime `json:"bannedAt"`
	Email    *string     `json:"email"`
	ID       string      `json:"id"`

	// SessionsRemoved 消したセッションの数（落とした画面の数）
	SessionsRemoved int `json:"sessionsRemoved"`
}

// AdminDeleteResult defines model for AdminDeleteResult.
type AdminDeleteResult struct {
	Email *string `json:"email"`
	ID    string  `json:"id"`

	// Removed 一緒に消えた行数（記録のためだけ。消すのは外部キーの CASCADE）
	Removed struct {
		FinalGoals int `json:"finalGoals"`
		StudyLogs  int `json:"studyLogs"`
		StudyPlans int `json:"studyPlans"`
		Textbooks  int `json:"textbooks"`
	} `json:"removed"`
}

// AdminFaculty defines model for AdminFaculty.
type AdminFaculty struct {
	// ExamDate YYYY-MM-DD（UTC の0時で保存している日付部分）
	ExamDate string `json:"examDate"`

	// GoalCount この学部を志望校にしている件数。1件でもあれば削除できない
	GoalCount int        `json:"goalCount"`
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	Tags      []AdminTag `json:"tags"`
}

// AdminFacultySnapshot 学部の作成・書き換えの応答（監査ログの「前・後」と同じ形）
type AdminFacultySnapshot struct {
	// ExamDate YYYY-MM-DD
	ExamDate     string  `json:"examDate"`
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	TagIds       []int64 `json:"tagIds"`
	UniversityID int64   `json:"universityId"`
}

// AdminOverview defines model for AdminOverview.
type AdminOverview struct {
	Kinds []KindStats `json:"kinds"`

	// RealSignupsByDay 実ユーザーの日別新規登録（日本時間の日付、直近30日。登録0の日は含まない）
	RealSignupsByDay []struct {
		Count int `json:"count"`

		// Date 日付だけ（"YYYY-MM-DD"、日本時間の日付）
		Date IsoDate `json:"date"`
	} `json:"realSignupsByDay"`
}

// AdminTag defines model for AdminTag.
type AdminTag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// AdminTextbookMaster defines model for AdminTextbookMaster.
type AdminTextbookMaster struct {
	Edition   *string                     `json:"edition"`
	ID        int64                       `json:"id"`
	Isbn      string                      `json:"isbn"`
	Metrics   []AdminTextbookMasterMetric `json:"metrics"`
	Name      string                      `json:"name"`
	Publisher *string                     `json:"publisher"`

	// TextbookCount この参考書から登録された利用者の参考書の数。1冊でもあれば削除できない
	TextbookCount int `json:"textbookCount"`
}

// AdminTextbookMasterMetric 参考書の総量の候補（単位ごと）
type AdminTextbookMasterMetric struct {
	// IsDefault 利用者が参考書を登録したとき、この候補で総量が入る
	IsDefault   bool   `json:"isDefault"`
	TotalAmount int    `json:"totalAmount"`
	Unit        string `json:"unit"`
}

// AdminUniversity defines model for AdminUniversity.
type AdminUniversity struct {
	FacultyCount int `json:"facultyCount"`

	// GoalCount 配下の学部を志望校にしている件数。1件でもあれば大学は削除できない
	GoalCount  int    `json:"goalCount"`
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Prefecture string `json:"prefecture"`

	// Type 国立・公立・私立
	Type string `json:"type"`
}

// AdminUniversityDetail defines model for AdminUniversityDetail.
type AdminUniversityDetail struct {
	Faculties  []AdminFaculty  `json:"faculties"`
	University AdminUniversity `json:"university"`
}

// AdminUniversityList defines model for AdminUniversityList.
type AdminUniversityList struct {
	Page         int               `json:"page"`
	PageSize     int               `json:"pageSize"`
	Total        int               `json:"total"`
	Universities []AdminUniversity `json:"universities"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	// BannedAt 管理者に停止された日時。null なら停止していない
	BannedAt *IsoDateTime `json:"bannedAt"`

	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt     IsoDateTime `json:"createdAt"`
	Email         *string     `json:"email"`
	EmailVerified bool        `json:"emailVerified"`
	ID            string      `json:"id"`

	// Kind 利用者の種別。real は実際の利用者、sim は本番のシミュレーション、seed は手元の負荷検証用、 demo は面接官向けのデモアカウント
	Kind           UserKind     `json:"kind"`
	LastLoginAt    *IsoDateTime `json:"lastLoginAt"`
	LastStudyLogAt *IsoDateTime `json:"lastStudyLogAt"`
	Name           *string      `json:"name"`
	Nickname       *string      `json:"nickname"`

	// Providers 認証方法（account.providerId）。credential はメール＋パスワード
	Providers     []string      `json:"providers"`
	Role          AdminUserRole `json:"role"`
	StudyLogCount int           `json:"studyLogCount"`
}

// AdminUserRole defines model for AdminUser.Role.
type AdminUserRole string

// AdminUserList defines model for AdminUserList.
type AdminUserList struct {
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
	Total    int         `json:"total"`
	Users    []AdminUser `json:"users"`
}

// AdminUserRef 操作した相手
type AdminUserRef struct {
	Email *string `json:"email"`
	ID    string  `json:"id"`
}

// CompleteStudyPlanInput 予定の完了（Zod の completeStudyPlanSchema）。範囲の3つの規則は StudyLogInput と同じ
type CompleteStudyPlanInput struct {
	Memo       *string                          `json:"memo,omitempty"`
	Minutes    int64                            `json:"minutes"`
	RangeEnd   *int64                           `json:"rangeEnd,omitempty"`
	RangeStart *int64                           `json:"rangeStart,omitempty"`
	RangeUnit  *CompleteStudyPlanInputRangeUnit `json:"rangeUnit,omitempty"`
}

// CompleteStudyPlanInputRangeUnit defines model for CompleteStudyPlanInput.RangeUnit.
type CompleteStudyPlanInputRangeUnit string

// CompletedStudyPlan defines model for CompletedStudyPlan.
type CompletedStudyPlan struct {
	IsFirstStudyLog bool `json:"isFirstStudyLog"`

	// Log 実績の行に、参考書の行（無ければ null）を付けたもの
	Log StudyLogWithTextbook `json:"log"`

	// Plan 予定の行（書き込みの応答）
	Plan StudyPlanRow `json:"plan"`
}

// CreateFacultyInput 学部の作成（Zod の createFacultySchema）。FacultyInput に大学を足したもの
type CreateFacultyInput struct {
	ExamDate string `json:"examDate"`

	// Name 前後の空白を削ってから数える
	Name         string  `json:"name"`
	TagIds       []int64 `json:"tagIds"`
	UniversityID int64   `json:"universityId"`
}

// CreatedCount defines model for CreatedCount.
type CreatedCount struct {
	Count int64 `json:"count"`
}

// CreatedStudyLog 記録した実績と、それがその人の最初の記録か
type CreatedStudyLog struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date            IsoDateTime `json:"date"`
	ID              int64       `json:"id"`
	IsFirstStudyLog bool        `json:"isFirstStudyLog"`
	Memo            *string     `json:"memo"`
	Minutes         int64       `json:"minutes"`
	RangeEnd        *int64      `json:"rangeEnd"`
	RangeStart      *int64      `json:"rangeStart"`
	RangeUnit       *string     `json:"rangeUnit"`
	StudyPlanID     *int64      `json:"studyPlanId"`
	Subject         *string     `json:"subject"`
	TextbookID      *int64      `json:"textbookId"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
	UserID    string      `json:"userId"`
}

// DailyStudyMinutes defines model for DailyStudyMinutes.
type DailyStudyMinutes struct {
	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date    IsoDateTime `json:"date"`
	Minutes int64       `json:"minutes"`
}

// Dashboard defines model for Dashboard.
type Dashboard struct {
	DailyMinutes []DailyStudyMinutes `json:"dailyMinutes"`

	// LogRange 両端を含む期間（"YYYY-MM-DD"）
	LogRange DateRange  `json:"logRange"`
	Logs     []StudyLog `json:"logs"`

	// Month 今日の月（"YYYY-MM"）
	Month string `json:"month"`

	// PlanRange 両端を含む期間（"YYYY-MM-DD"）
	PlanRange DateRange   `json:"planRange"`
	Plans     []StudyPlan `json:"plans"`
}

// DateRange 両端を含む期間（"YYYY-MM-DD"）
type DateRange struct {
	// From 日付だけ（"YYYY-MM-DD"、日本時間の日付）
	From IsoDate `json:"from"`

	// To 日付だけ（"YYYY-MM-DD"、日本時間の日付）
	To IsoDate `json:"to"`
}

// Deleted defines model for Deleted.
type Deleted struct {
	Message DeletedMessage `json:"message"`
}

// DeletedMessage defines model for Deleted.Message.
type DeletedMessage string

// Error ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type Error struct {
	Error string `json:"error"`
}

// ExploreFaculty defines model for ExploreFaculty.
type ExploreFaculty struct {
	Tags []ExploreTag `json:"tags"`
}

// ExploreTag defines model for ExploreTag.
type ExploreTag struct {
	Name string `json:"name"`
}

// ExploreUniversity 大学を探す画面の1件。画面が使うのは大学の列と学部ごとのタグ名だけ。 Go はこの形を手書きの型で返す（Go へ移したときに JSON のキーの順番と ETag を以前と同じにするため）
type ExploreUniversity struct {
	Faculties  []ExploreFaculty `json:"faculties"`
	ID         int64            `json:"id"`
	Name       string           `json:"name"`
	Prefecture string           `json:"prefecture"`
	Type       string           `json:"type"`
}

// Faculty 学部（大学を入れ子にしない）
type Faculty struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// ExamDate Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	ExamDate     IsoDateTime `json:"examDate"`
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	UniversityID int64       `json:"universityId"`
}

// FacultyInput 学部の書き換え（Zod の facultyInputSchema）。受験日は YYYY-MM-DD で、JavaScript の new Date と同じく 日は 31 まで受け付けて繰り上げる（2027-02-30 は 3月2日）。タグは重ねられない
type FacultyInput struct {
	ExamDate string `json:"examDate"`

	// Name 前後の空白を削ってから数える
	Name   string  `json:"name"`
	TagIds []int64 `json:"tagIds"`
}

// FacultyWithTags defines model for FacultyWithTags.
type FacultyWithTags struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// ExamDate Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	ExamDate     IsoDateTime `json:"examDate"`
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Tags         []Tag       `json:"tags"`
	UniversityID int64       `json:"universityId"`
}

// FacultyWithUniversity defines model for FacultyWithUniversity.
type FacultyWithUniversity struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// ExamDate Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	ExamDate     IsoDateTime `json:"examDate"`
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	University   University  `json:"university"`
	UniversityID int64       `json:"universityId"`
}

// FacultyWithUniversityAndTags defines model for FacultyWithUniversityAndTags.
type FacultyWithUniversityAndTags struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// ExamDate Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	ExamDate     IsoDateTime `json:"examDate"`
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Tags         []Tag       `json:"tags"`
	University   University  `json:"university"`
	UniversityID int64       `json:"universityId"`
}

// FirstChoiceGoal 第一志望。学部・大学つき（タグは付けない）
type FirstChoiceGoal struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt     IsoDateTime           `json:"createdAt"`
	Faculty       FacultyWithUniversity `json:"faculty"`
	FacultyID     int64                 `json:"facultyId"`
	ID            int64                 `json:"id"`
	IsFirstChoice bool                  `json:"isFirstChoice"`
	Note          *string               `json:"note"`
	Status        string                `json:"status"`
	UserID        string                `json:"userId"`
}

// Goal 志望校の一覧の1件。学部・大学・学部のタグつき
type Goal struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt     IsoDateTime                  `json:"createdAt"`
	Faculty       FacultyWithUniversityAndTags `json:"faculty"`
	FacultyID     int64                        `json:"facultyId"`
	ID            int64                        `json:"id"`
	IsFirstChoice bool                         `json:"isFirstChoice"`
	Note          *string                      `json:"note"`
	Status        string                       `json:"status"`
	UserID        string                       `json:"userId"`
}

// GoalFields 志望校の列（学部は含まない）
type GoalFields struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt     IsoDateTime `json:"createdAt"`
	FacultyID     int64       `json:"facultyId"`
	ID            int64       `json:"id"`
	IsFirstChoice bool        `json:"isFirstChoice"`
	Note          *string     `json:"note"`
	Status        string      `json:"status"`
	UserID        string      `json:"userId"`
}

// GoalInput 志望校の登録（Zod の goalSchema）。status を省くと decided
type GoalInput struct {
	FacultyID int64            `json:"facultyId"`
	Status    *GoalInputStatus `json:"status,omitempty"`
}

// GoalInputStatus defines model for GoalInput.Status.
type GoalInputStatus string

// GoalPatchInput 第一志望・メモ・ステータスの書き換え（Zod の patchGoalSchema）。送った項目だけを書き換える
type GoalPatchInput struct {
	IsFirstChoice *bool                 `json:"isFirstChoice,omitempty"`
	Note          *string               `json:"note,omitempty"`
	Status        *GoalPatchInputStatus `json:"status,omitempty"`
}

// GoalPatchInputStatus defines model for GoalPatchInput.Status.
type GoalPatchInputStatus string

// GoalUpdateInput 学部の差し替え（Zod の updateGoalSchema。goalSchema の全項目を任意にしたもの）
type GoalUpdateInput struct {
	FacultyID *int64                 `json:"facultyId,omitempty"`
	Status    *GoalUpdateInputStatus `json:"status,omitempty"`
}

// GoalUpdateInputStatus defines model for GoalUpdateInput.Status.
type GoalUpdateInputStatus string

// IsoDate 日付だけ（"YYYY-MM-DD"、日本時間の日付）
type IsoDate = string

// IsoDateTime Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
type IsoDateTime = string

// KindStats defines model for KindStats.
type KindStats struct {
	ActiveLast30Days int `json:"activeLast30Days"`

	// ActiveLast7Days 直近7日に学習記録を作った人（記録した日時で数える）
	ActiveLast7Days int `json:"activeLast7Days"`

	// Kind 利用者の種別。real は実際の利用者、sim は本番のシミュレーション、seed は手元の負荷検証用、 demo は面接官向けのデモアカウント
	Kind         UserKind `json:"kind"`
	NewLast7Days int      `json:"newLast7Days"`
	Total        int      `json:"total"`
	Verified     int      `json:"verified"`
}

// LineConnectionStatus defines model for LineConnectionStatus.
type LineConnectionStatus struct {
	Connected bool `json:"connected"`
}

// NotificationPreference defines model for NotificationPreference.
type NotificationPreference struct {
	EmailEveningEnabled bool `json:"emailEveningEnabled"`
	EmailMorningEnabled bool `json:"emailMorningEnabled"`
	LineEveningEnabled  bool `json:"lineEveningEnabled"`
	LineMorningEnabled  bool `json:"lineMorningEnabled"`
}

// NotificationSlot defines model for NotificationSlot.
type NotificationSlot string

// NotificationSummary defines model for NotificationSummary.
type NotificationSummary struct {
	// Date 日付だけ（"YYYY-MM-DD"、日本時間の日付）
	Date     IsoDate          `json:"date"`
	Eligible int64            `json:"eligible"`
	Failed   int64            `json:"failed"`
	Sent     int64            `json:"sent"`
	Skipped  int64            `json:"skipped"`
	Slot     NotificationSlot `json:"slot"`
}

// OkMessage defines model for OkMessage.
type OkMessage struct {
	Message OkMessageMessage `json:"message"`
}

// OkMessageMessage defines model for OkMessage.Message.
type OkMessageMessage string

// ProfileInput プロフィールの更新（Zod の profileSchema）。長さはコードポイントの数（絵文字も1）で数え、 前後の空白は長さを確かめた後に削る（空白だけでも通り、空文字で保存される）
type ProfileInput struct {
	Nickname string `json:"nickname"`
}

// RegistrationTracking defines model for RegistrationTracking.
type RegistrationTracking struct {
	// Method 登録に使った方法（最初に作られたアカウント）。shouldTrack が true のときだけ
	Method      *RegistrationTrackingMethod `json:"method,omitempty"`
	ShouldTrack bool                        `json:"shouldTrack"`
}

// RegistrationTrackingMethod 登録に使った方法（最初に作られたアカウント）。shouldTrack が true のときだけ
type RegistrationTrackingMethod string

// ServerError 想定外の失敗・混雑・存在しないパス
type ServerError struct {
	Code  ServerErrorCode `json:"code"`
	Error string          `json:"error"`
	ReqID string          `json:"reqId"`
}

// ServerErrorCode defines model for ServerError.Code.
type ServerErrorCode string

// SimulationCohort 合成ユーザーの続き方の型
type SimulationCohort string

// SimulationState defines model for SimulationState.
type SimulationState struct {
	// NextSeq 次に使う連番（最後の連番＋1。だれもいなければ 1）
	NextSeq int64            `json:"nextSeq"`
	Users   []SimulationUser `json:"users"`
}

// SimulationUser defines model for SimulationUser.
type SimulationUser struct {
	// Cohort DB の値をそのまま返す（書き込みは SimulationCohort に限っている）
	Cohort string `json:"cohort"`

	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt   IsoDateTime `json:"createdAt"`
	DormantFrom *IsoDate    `json:"dormantFrom"`
	Email       string      `json:"email"`
	LastActedOn *IsoDate    `json:"lastActedOn"`
	Seq         int64       `json:"seq"`
}

// SimulationUserMark defines model for SimulationUserMark.
type SimulationUserMark struct {
	// Cohort 合成ユーザーの続き方の型
	Cohort SimulationCohort `json:"cohort"`

	// Email シミュレーション用のアドレス（delivered+simNNNNN@resend.dev）だけ
	Email string `json:"email"`
	Seq   int64  `json:"seq"`
}

// SimulationUserUpdate キーが無い項目は変えない。null なら消す
type SimulationUserUpdate struct {
	DormantFrom *IsoDate `json:"dormantFrom,omitempty"`
	LastActedOn *IsoDate `json:"lastActedOn,omitempty"`
}

// StudyLog defines model for StudyLog.
type StudyLog struct {
	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date        IsoDateTime `json:"date"`
	ID          int64       `json:"id"`
	Memo        *string     `json:"memo"`
	Minutes     int64       `json:"minutes"`
	RangeEnd    *int64      `json:"rangeEnd"`
	RangeStart  *int64      `json:"rangeStart"`
	RangeUnit   *string     `json:"rangeUnit"`
	StudyPlanID *int64      `json:"studyPlanId"`
	Subject     *string     `json:"subject"`
	Textbook    *Textbook   `json:"textbook"`
	TextbookID  *int64      `json:"textbookId"`
}

// StudyLogInput 実績の記録・書き換え（Zod の createStudyLogSchema）。項目をまたぐ規則はスキーマに書けないので、ここには無い： 範囲の開始と終了はそろえて送る（range_incomplete）、開始 ≦ 終了（range_end_before_start）、 範囲を送ったら単位も送る（range_unit_required）、日付は今日（日本時間）以前（future_date）。 参考書を指定したら、自分の参考書で、範囲が参考書の単位と総量に合うこと（Error の 400）
type StudyLogInput struct {
	// Date 暦にある日付（invalid_format・invalid_date）
	Date string `json:"date"`

	// Memo 500文字（コードポイント）まで。前後の空白は削る。null は不可
	Memo       *string                 `json:"memo,omitempty"`
	Minutes    int64                   `json:"minutes"`
	RangeEnd   *int64                  `json:"rangeEnd,omitempty"`
	RangeStart *int64                  `json:"rangeStart,omitempty"`
	RangeUnit  *StudyLogInputRangeUnit `json:"rangeUnit,omitempty"`
	Subject    *StudyLogInputSubject   `json:"subject,omitempty"`
	TextbookID *int64                  `json:"textbookId,omitempty"`
}

// StudyLogInputRangeUnit defines model for StudyLogInput.RangeUnit.
type StudyLogInputRangeUnit string

// StudyLogInputSubject defines model for StudyLogInput.Subject.
type StudyLogInputSubject string

// StudyLogRow 実績の行（書き込みの応答。一覧の StudyLog と違い、参考書は入れ子にせず userId・日時を持つ）
type StudyLogRow struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date        IsoDateTime `json:"date"`
	ID          int64       `json:"id"`
	Memo        *string     `json:"memo"`
	Minutes     int64       `json:"minutes"`
	RangeEnd    *int64      `json:"rangeEnd"`
	RangeStart  *int64      `json:"rangeStart"`
	RangeUnit   *string     `json:"rangeUnit"`
	StudyPlanID *int64      `json:"studyPlanId"`
	Subject     *string     `json:"subject"`
	TextbookID  *int64      `json:"textbookId"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
	UserID    string      `json:"userId"`
}

// StudyLogWithTextbook 実績の行に、参考書の行（無ければ null）を付けたもの
type StudyLogWithTextbook struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date        IsoDateTime  `json:"date"`
	ID          int64        `json:"id"`
	Memo        *string      `json:"memo"`
	Minutes     int64        `json:"minutes"`
	RangeEnd    *int64       `json:"rangeEnd"`
	RangeStart  *int64       `json:"rangeStart"`
	RangeUnit   *string      `json:"rangeUnit"`
	StudyPlanID *int64       `json:"studyPlanId"`
	Subject     *string      `json:"subject"`
	Textbook    *TextbookRow `json:"textbook"`
	TextbookID  *int64       `json:"textbookId"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
	UserID    string      `json:"userId"`
}

// StudyPlan defines model for StudyPlan.
type StudyPlan struct {
	Content *string `json:"content"`

	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date       IsoDateTime `json:"date"`
	Done       bool        `json:"done"`
	ID         int64       `json:"id"`
	RangeEnd   *int64      `json:"rangeEnd"`
	RangeStart *int64      `json:"rangeStart"`
	RangeUnit  *string     `json:"rangeUnit"`
	StudyLogID *int64      `json:"studyLogId"`
	Subject    *string     `json:"subject"`
	Textbook   *Textbook   `json:"textbook"`
	TextbookID *int64      `json:"textbookId"`
}

// StudyPlanItemInput 予定1件（Zod の studyPlanItemSchema）。スキーマに書けない規則：範囲の3つ（StudyLogInput と同じ）と、 参考書・範囲・メモのどれかが要る（plan_content_required。メモは前後の空白を削った後で見る）
type StudyPlanItemInput struct {
	// Content 500文字（コードポイント）まで。前後の空白は削る。null は不可
	Content    *string                      `json:"content,omitempty"`
	RangeEnd   *int64                       `json:"rangeEnd,omitempty"`
	RangeStart *int64                       `json:"rangeStart,omitempty"`
	RangeUnit  *StudyPlanItemInputRangeUnit `json:"rangeUnit,omitempty"`
	Subject    *StudyPlanItemInputSubject   `json:"subject,omitempty"`
	TextbookID *int64                       `json:"textbookId,omitempty"`
}

// StudyPlanItemInputRangeUnit defines model for StudyPlanItemInput.RangeUnit.
type StudyPlanItemInputRangeUnit string

// StudyPlanItemInputSubject defines model for StudyPlanItemInput.Subject.
type StudyPlanItemInputSubject string

// StudyPlanRow 予定の行（書き込みの応答）
type StudyPlanRow struct {
	Content *string `json:"content"`

	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`

	// Date Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	Date       IsoDateTime `json:"date"`
	Done       bool        `json:"done"`
	ID         int64       `json:"id"`
	RangeEnd   *int64      `json:"rangeEnd"`
	RangeStart *int64      `json:"rangeStart"`
	RangeUnit  *string     `json:"rangeUnit"`
	Subject    *string     `json:"subject"`
	TextbookID *int64      `json:"textbookId"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
	UserID    string      `json:"userId"`
}

// StudyPlanUpdateInput 予定の書き換え（Zod の updateStudyPlanSchema）。送った項目だけを書き換える。null を送れる項目は、 null で「空にする」。範囲の3つの規則は StudyLogInput と同じ
type StudyPlanUpdateInput struct {
	Content    *string                        `json:"content,omitempty"`
	Date       *string                        `json:"date,omitempty"`
	Done       *bool                          `json:"done,omitempty"`
	RangeEnd   *int64                         `json:"rangeEnd,omitempty"`
	RangeStart *int64                         `json:"rangeStart,omitempty"`
	RangeUnit  *StudyPlanUpdateInputRangeUnit `json:"rangeUnit,omitempty"`
	Subject    *StudyPlanUpdateInputSubject   `json:"subject,omitempty"`
	TextbookID *int64                         `json:"textbookId,omitempty"`
}

// StudyPlanUpdateInputRangeUnit defines model for StudyPlanUpdateInput.RangeUnit.
type StudyPlanUpdateInputRangeUnit string

// StudyPlanUpdateInputSubject defines model for StudyPlanUpdateInput.Subject.
type StudyPlanUpdateInputSubject string

// StudyPlansInput 予定の作成（Zod の createStudyPlansSchema）。日付は暦にある YYYY-MM-DD（未来も可）
type StudyPlansInput struct {
	Date  string               `json:"date"`
	Items []StudyPlanItemInput `json:"items"`
}

// Tag defines model for Tag.
type Tag struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
}

// Textbook 実績・予定に JOIN した参考書（表示用）
type Textbook struct {
	ID          int64        `json:"id"`
	MasterID    *int64       `json:"masterId"`
	Name        string       `json:"name"`
	RangeUnit   *string      `json:"rangeUnit"`
	Subject     *string      `json:"subject"`
	TargetDate  *IsoDateTime `json:"targetDate"`
	TotalAmount *int64       `json:"totalAmount"`
}

// TextbookFromMasterInput defines model for TextbookFromMasterInput.
type TextbookFromMasterInput struct {
	MasterID int64 `json:"masterId"`
}

// TextbookInput 参考書の登録（Zod の createTextbookSchema）。名前で作る形が先に当たる（両方送ると名前で作る）。 どちらにも当たらなければ invalid_union（field は null）。Go は本文を手で読む（textbook_writes.go）ので、 oneOf の型は作らない（作ると oapi-codegen の runtime への依存が増える）
type TextbookInput = any

// TextbookMaster defines model for TextbookMaster.
type TextbookMaster struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt IsoDateTime `json:"createdAt"`
	Edition   *string     `json:"edition"`
	ID        int64       `json:"id"`
	ISBN      string      `json:"isbn"`

	// Metrics 総量の候補（id 順）。無くても []
	Metrics   []TextbookMasterMetric `json:"metrics"`
	Name      string                 `json:"name"`
	Publisher *string                `json:"publisher"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
}

// TextbookMasterInput 参考書マスターの作成・書き換え（Zod の textbookMasterInputSchema）。スキーマに書けない規則：総量の候補は 単位が重ならず（duplicate_units）、既定（isDefault）がちょうど1つ（default_unit_required）
type TextbookMasterInput struct {
	// Edition 前後の空白を削り、空なら null で保存する
	Edition *string `json:"edition,omitempty"`

	// Isbn ハイフン・空白を除き大文字にしてから、10桁（最後は X 可）か13桁
	Isbn    string `json:"isbn"`
	Metrics []struct {
		IsDefault   bool                           `json:"isDefault"`
		TotalAmount int                            `json:"totalAmount"`
		Unit        TextbookMasterInputMetricsUnit `json:"unit"`
	} `json:"metrics"`

	// Name 前後の空白を削ってから数える
	Name string `json:"name"`

	// Publisher 前後の空白を削り、空なら null で保存する
	Publisher *string `json:"publisher,omitempty"`
}

// TextbookMasterInputMetricsUnit defines model for TextbookMasterInput.Metrics.Unit.
type TextbookMasterInputMetricsUnit string

// TextbookMasterMetric defines model for TextbookMasterMetric.
type TextbookMasterMetric struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt   IsoDateTime `json:"createdAt"`
	ID          int64       `json:"id"`
	IsDefault   bool        `json:"isDefault"`
	MasterID    int64       `json:"masterId"`
	TotalAmount int64       `json:"totalAmount"`
	Unit        string      `json:"unit"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
}

// TextbookNameInput defines model for TextbookNameInput.
type TextbookNameInput struct {
	// Name 前後の空白を削ってから長さを確かめる
	Name      string                      `json:"name"`
	RangeUnit *TextbookNameInputRangeUnit `json:"rangeUnit,omitempty"`
	Subject   *TextbookNameInputSubject   `json:"subject,omitempty"`
}

// TextbookNameInputRangeUnit defines model for TextbookNameInput.RangeUnit.
type TextbookNameInputRangeUnit string

// TextbookNameInputSubject defines model for TextbookNameInput.Subject.
type TextbookNameInputSubject string

// TextbookProgressInput 逆算設定の書き換え（Zod の updateTextbookProgressSchema）。送った項目だけを書き換える
type TextbookProgressInput struct {
	RangeUnit *TextbookProgressInputRangeUnit `json:"rangeUnit,omitempty"`
	Subject   *TextbookProgressInputSubject   `json:"subject,omitempty"`

	// TargetDate 暦にある日付（Zod の z.iso.date()）
	TargetDate  *string `json:"targetDate,omitempty"`
	TotalAmount *int64  `json:"totalAmount,omitempty"`
}

// TextbookProgressInputRangeUnit defines model for TextbookProgressInput.RangeUnit.
type TextbookProgressInputRangeUnit string

// TextbookProgressInputSubject defines model for TextbookProgressInput.Subject.
type TextbookProgressInputSubject string

// TextbookRow 自分の参考書（DB の行そのまま）
type TextbookRow struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt   IsoDateTime  `json:"createdAt"`
	ID          int64        `json:"id"`
	MasterID    *int64       `json:"masterId"`
	Name        string       `json:"name"`
	RangeUnit   *string      `json:"rangeUnit"`
	Subject     *string      `json:"subject"`
	TargetDate  *IsoDateTime `json:"targetDate"`
	TotalAmount *int64       `json:"totalAmount"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
	UserID    string      `json:"userId"`
}

// University defines model for University.
type University struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt  IsoDateTime `json:"createdAt"`
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Prefecture string      `json:"prefecture"`
	Type       string      `json:"type"`
}

// UniversityDetail defines model for UniversityDetail.
type UniversityDetail struct {
	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt  IsoDateTime       `json:"createdAt"`
	Faculties  []FacultyWithTags `json:"faculties"`
	ID         int64             `json:"id"`
	Name       string            `json:"name"`
	Prefecture string            `json:"prefecture"`
	Type       string            `json:"type"`
}

// UniversityDetailResponse defines model for UniversityDetailResponse.
type UniversityDetailResponse struct {
	// RegisteredFacultyIds 自分が志望校に登録済みの学部 ID（昇順）
	RegisteredFacultyIds []int64          `json:"registeredFacultyIds"`
	University           UniversityDetail `json:"university"`
}

// UniversityInput 大学の作成・書き換え（Zod の universityInputSchema）
type UniversityInput struct {
	// Name 前後の空白を削ってから数える
	Name string `json:"name"`

	// Prefecture 47都道府県のどれか（src/shared/prefectures.ts の PREFECTURES）
	Prefecture string              `json:"prefecture"`
	Type       UniversityInputType `json:"type"`
}

// UniversityInputType defines model for UniversityInput.Type.
type UniversityInputType string

// User 利用者の行（PUT /api/profile が返す）
type User struct {
	AnalyticsSignUpTrackedAt *IsoDateTime `json:"analyticsSignUpTrackedAt"`

	// CreatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	CreatedAt       IsoDateTime  `json:"createdAt"`
	Email           *string      `json:"email"`
	EmailVerified   bool         `json:"emailVerified"`
	FirstStudyLogAt *IsoDateTime `json:"firstStudyLogAt"`
	ID              string       `json:"id"`
	Image           *string      `json:"image"`
	Name            *string      `json:"name"`
	Nickname        *string      `json:"nickname"`

	// UpdatedAt Date を JSON にしたときの ISO 文字列（例 "2026-09-24T00:00:00.000Z"）
	UpdatedAt IsoDateTime `json:"updatedAt"`
}

// UserKind 利用者の種別。real は実際の利用者、sim は本番のシミュレーション、seed は手元の負荷検証用、 demo は面接官向けのデモアカウント
type UserKind string

// ValidationError 入力チェックで弾いたときのエラー（Go の internal/httpx/response.go）
type ValidationError struct {
	// Code 種類。自分で書いた規則は名前（range_end_before_start など）、 組み込みのチェックは Zod の code（too_small・invalid_type・invalid_format など）
	Code string `json:"code"`

	// Error 画面にそのまま出す文言
	Error string `json:"error"`

	// Field どの項目か（"rangeEnd"・"items.0.unit"）。項目に結びつかなければ null
	Field *string `json:"field"`
}

// AdminMasterID defines model for AdminMasterID.
type AdminMasterID = string

// AdminUserID defines model for AdminUserID.
type AdminUserID = string

// From defines model for From.
type From = string

// ID defines model for ID.
type ID = string

// To defines model for To.
type To = string

// AdminFacultyBadRequest ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type AdminFacultyBadRequest = Error

// AdminForbidden ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type AdminForbidden = Error

// AdminMasterConflict ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type AdminMasterConflict = Error

// AdminUserProtected ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type AdminUserProtected = Error

// BadRequest ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type BadRequest = Error

// Forbidden ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type Forbidden = Error

// InternalError 想定外の失敗・混雑・存在しないパス
type InternalError = ServerError

// NotFound ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type NotFound = Error

// PayloadTooLarge 想定外の失敗・混雑・存在しないパス
type PayloadTooLarge = ServerError

// Unauthorized ルートが自分で断るときのエラー。error は画面にそのまま出す文言
type Unauthorized = Error

// UnsupportedMediaType 想定外の失敗・混雑・存在しないパス
type UnsupportedMediaType = ServerError

// ListAdminTextbookMastersParams defines parameters for ListAdminTextbookMasters.
type ListAdminTextbookMastersParams struct {
	// Q 前後の空白を削ってから100文字（コードポイント）まで。空なら絞らない
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListAdminUniversitiesParams defines parameters for ListAdminUniversities.
type ListAdminUniversitiesParams struct {
	// Q 大学名の部分一致。前後の空白を削ってから100文字（コードポイント）まで。空なら絞らない
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Page 1から。省くと 1。数として読める文字列なら受け付ける（Zod の coerce）
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// ListAdminUsersParams defines parameters for ListAdminUsers.
type ListAdminUsersParams struct {
	// Kind 省くと real
	Kind *UserKind `form:"kind,omitempty" json:"kind,omitempty"`

	// Q メールアドレスの部分一致（前後の空白は無視）
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Page 1から。省くと 1。数として読める文字列なら受け付ける（Zod の coerce）
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// DeleteUserJSONBody defines parameters for DeleteUser.
type DeleteUserJSONBody struct {
	// Email 大文字小文字と前後の空白は無視して比べる
	Email string `json:"email"`
}

// SendDailyStudyNotificationsJSONBody defines parameters for SendDailyStudyNotifications.
type SendDailyStudyNotificationsJSONBody struct {
	Slot NotificationSlot `json:"slot"`
}

// ReportCspViolationApplicationReportsPlusJSONBody defines parameters for ReportCspViolation.
type ReportCspViolationApplicationReportsPlusJSONBody = []map[string]interface{}

// GetHealth200JSONResponseBodyOk defines parameters for GetHealth.
type GetHealth200JSONResponseBodyOk bool

// StartLineAccountLinkJSONBody defines parameters for StartLineAccountLink.
type StartLineAccountLinkJSONBody struct {
	LinkToken string `json:"linkToken"`
}

// CompleteLineLoginParams defines parameters for CompleteLineLogin.
type CompleteLineLoginParams struct {
	State *string `form:"state,omitempty" json:"state,omitempty"`
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// ReceiveLineWebhookJSONBody defines parameters for ReceiveLineWebhook.
type ReceiveLineWebhookJSONBody = map[string]interface{}

// ReceiveLineWebhookParams defines parameters for ReceiveLineWebhook.
type ReceiveLineWebhookParams struct {
	XLineSignature string `json:"x-line-signature"`
}

// ReceiveLineWebhook200JSONResponseBodyOk defines parameters for ReceiveLineWebhook.
type ReceiveLineWebhook200JSONResponseBodyOk bool

// ListStudyLogsParams defines parameters for ListStudyLogs.
type ListStudyLogsParams struct {
	// From 期間の始まり（その日を含む）
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To 期間の終わり（その日を含む）
	To *To `form:"to,omitempty" json:"to,omitempty"`
}

// ListDailyStudyMinutesParams defines parameters for ListDailyStudyMinutes.
type ListDailyStudyMinutesParams struct {
	// From 期間の始まり（その日を含む）
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To 期間の終わり（その日を含む）
	To *To `form:"to,omitempty" json:"to,omitempty"`
}

// ListStudyPlansParams defines parameters for ListStudyPlans.
type ListStudyPlansParams struct {
	// From 期間の始まり（その日を含む）
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To 期間の終わり（その日を含む）
	To *To `form:"to,omitempty" json:"to,omitempty"`
}

// ListTextbookMastersParams defines parameters for ListTextbookMasters.
type ListTextbookMastersParams struct {
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// ListUniversitiesParams defines parameters for ListUniversities.
type ListUniversitiesParams struct {
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// ReceiveMicrocmsWebhookJSONBody defines parameters for ReceiveMicrocmsWebhook.
type ReceiveMicrocmsWebhookJSONBody = map[string]interface{}

// ReceiveMicrocmsWebhookParams defines parameters for ReceiveMicrocmsWebhook.
type ReceiveMicrocmsWebhookParams struct {
	XMicrocmsSignature string `json:"x-microcms-signature"`
}

// ReceiveMicrocmsWebhook200JSONResponseBodyDeploy defines parameters for ReceiveMicrocmsWebhook.
type ReceiveMicrocmsWebhook200JSONResponseBodyDeploy string

// CreateFacultyJSONRequestBody defines body for CreateFaculty for application/json ContentType.
type CreateFacultyJSONRequestBody = CreateFacultyInput

// UpdateFacultyJSONRequestBody defines body for UpdateFaculty for application/json ContentType.
type UpdateFacultyJSONRequestBody = FacultyInput

// CreateTextbookMasterJSONRequestBody defines body for CreateTextbookMaster for application/json ContentType.
type CreateTextbookMasterJSONRequestBody = TextbookMasterInput

// UpdateTextbookMasterJSONRequestBody defines body for UpdateTextbookMaster for application/json ContentType.
type UpdateTextbookMasterJSONRequestBody = TextbookMasterInput

// CreateUniversityJSONRequestBody defines body for CreateUniversity for application/json ContentType.
type CreateUniversityJSONRequestBody = UniversityInput

// UpdateUniversityJSONRequestBody defines body for UpdateUniversity for application/json ContentType.
type UpdateUniversityJSONRequestBody = UniversityInput

// DeleteUserJSONRequestBody defines body for DeleteUser for application/json ContentType.
type DeleteUserJSONRequestBody DeleteUserJSONBody

// SendDailyStudyNotificationsJSONRequestBody defines body for SendDailyStudyNotifications for application/json ContentType.
type SendDailyStudyNotificationsJSONRequestBody SendDailyStudyNotificationsJSONBody

// ReportCspViolationApplicationReportsPlusJSONRequestBody defines body for ReportCspViolation for application/reports+json ContentType.
type ReportCspViolationApplicationReportsPlusJSONRequestBody = ReportCspViolationApplicationReportsPlusJSONBody

// CreateGoalJSONRequestBody defines body for CreateGoal for application/json ContentType.
type CreateGoalJSONRequestBody = GoalInput

// UpdateGoalJSONRequestBody defines body for UpdateGoal for application/json ContentType.
type UpdateGoalJSONRequestBody = GoalPatchInput

// ReplaceGoalFacultyJSONRequestBody defines body for ReplaceGoalFaculty for application/json ContentType.
type ReplaceGoalFacultyJSONRequestBody = GoalUpdateInput

// StartLineAccountLinkJSONRequestBody defines body for StartLineAccountLink for application/json ContentType.
type StartLineAccountLinkJSONRequestBody StartLineAccountLinkJSONBody

// ReceiveLineWebhookJSONRequestBody defines body for ReceiveLineWebhook for application/json ContentType.
type ReceiveLineWebhookJSONRequestBody = ReceiveLineWebhookJSONBody

// SaveNotificationPreferencesJSONRequestBody defines body for SaveNotificationPreferences for application/json ContentType.
type SaveNotificationPreferencesJSONRequestBody = NotificationPreference

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = ProfileInput

// MarkSimulationUserJSONRequestBody defines body for MarkSimulationUser for application/json ContentType.
type MarkSimulationUserJSONRequestBody = SimulationUserMark

// UpdateSimulationUserJSONRequestBody defines body for UpdateSimulationUser for application/json ContentType.
type UpdateSimulationUserJSONRequestBody = SimulationUserUpdate

// CreateStudyLogJSONRequestBody defines body for CreateStudyLog for application/json ContentType.
type CreateStudyLogJSONRequestBody = StudyLogInput

// UpdateStudyLogJSONRequestBody defines body for UpdateStudyLog for application/json ContentType.
type UpdateStudyLogJSONRequestBody = StudyLogInput

// CreateStudyPlansJSONRequestBody defines body for CreateStudyPlans for application/json ContentType.
type CreateStudyPlansJSONRequestBody = StudyPlansInput

// UpdateStudyPlanJSONRequestBody defines body for UpdateStudyPlan for application/json ContentType.
type UpdateStudyPlanJSONRequestBody = StudyPlanUpdateInput

// CompleteStudyPlanJSONRequestBody defines body for CompleteStudyPlan for application/json ContentType.
type CompleteStudyPlanJSONRequestBody = CompleteStudyPlanInput

// CreateTextbookJSONRequestBody defines body for CreateTextbook for application/json ContentType.
type CreateTextbookJSONRequestBody = TextbookInput

// UpdateTextbookProgressJSONRequestBody defines body for UpdateTextbookProgress for application/json ContentType.
type UpdateTextbookProgressJSONRequestBody = TextbookProgressInput

// ReceiveMicrocmsWebhookJSONRequestBody defines body for ReceiveMicrocmsWebhook for application/json ContentType.
type ReceiveMicrocmsWebhookJSONRequestBody = ReceiveMicrocmsWebhookJSONBody
